---
- name: Deploy Calculator Application
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: true
  tasks:
    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Pull Calculator Docker image
      docker_image:
        name: kevinadesara/calculator:latest
        source: pull

    - name: Ensure Calculator container is running
      docker_container:
        name: Calculator
        image: kevinadesara/calculator:latest
        state: started
        restart_policy: unless-stopped
        detach: true
        tty: true